### PR TITLE
add lint check in CI

### LINKED ISSUE #288: Add Lint Check in CI to improve code formatting.
**Describe the feature you'd like**

Add Lint Check to improve code formatting. 

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by hemilpanchiwala**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
Fixes #288 

Add Lint Check to improve code formatting.

## Screenshots
Successful lint check

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
Nice Job! Can you also add ./gradlew ktlint in script section of .travis.yml

**Comment by ujjwalagrawal17** [comment]
Thanks @hemilpanchiwala

**Comment by ujjwalagrawal17** [comment]
Did you used a command to fix the lint errors  @hemilpanchiwala ?

**Comment by hemilpanchiwala** [comment]
@ujjwalagrawal17 Yes, I used ktlintFormat command

**Pull request merged**
