### PR TITLE
New fragment profile stats: Removed hardcoded string 

### PR DESCRIPTION
**Pull request by gconnect**
** What this PR does**
- This PR fix change the hardcoded string in Profile Stat Fragment and removed the suppress annotation

**FIxes Issue**
Fixes #225 #203

### CODE REVIEW

**Comment by gconnect** [comment]
@victorvicari thanks.

**Comment by ujjwalagrawal17** [comment]
I am facing crash on opening profile fragment. 

**Relevant Logs:**

`2019-12-17 23:05:03.458 1529-1529/org.wikiedufoundation.wikiedudashboard.release E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wikiedufoundation.wikiedudashboard.release, PID: 1529
    java.lang.IllegalStateException: Fragment ProfileStatsFragment{dc4d400 (2e90b6d9-bdad-4029-b186-5aa575c0fef3)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:838)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.view.ProfileStatsFragment.<init>(ProfileStatsFragment.kt:40)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.view.ProfileStatsFragment$Companion.newInstance(ProfileStatsFragment.kt:108)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.view.ProfileFragment.setTabs(ProfileFragment.kt:132)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.view.ProfileFragment.setData(ProfileFragment.kt:166)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.ProfilePresenterImpl$requestProfile$1.onSuccess(ProfilePresenterImpl.kt:44)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.RetrofitProfileProvider$requestProfile$1.onResponse(RetrofitProfileProvider.kt:27)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

**Comment by victorvicari** [comment]
Instead of use the global variable `Resource`, an idea would be access the android resource through `context`. This way you can guarantee that it will have a `context` available. Just a tip.

**Comment by ujjwalagrawal17** [comment]
Screenshot 2019-12-17 at 11 24 50 pm


Also, I am able to see some issues in the UI. Can you see the UI issues in your PC too?

**Comment by gconnect** [comment]
> Can you fix the UI issues and the crash @gconnect ?
Yes I have fixed it.
image

**Comment by gconnect** [comment]
> Can you fix the UI issues and the crash @gconnect ?

Done

**Comment by ujjwalagrawal17** [comment]
Nice job! Thanks @gconnect

**Pull request merged**
