### PR TITLE
Fragment image viewer

### PR DESCRIPTION
**Pull request by gconnect**
** What does this PR do?**
- This PR change the RelativeLayout to Constraint Layout

**Comments**
-UI remains the both before and after

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
The change should ideally be in just 1 XML file. Can you revert minor changes in other files. (in other PRs too).. You should work in a seperate branch for all issues.

**Comment by gconnect** [comment]
Okay. Will do that sorry about that. I created a separate branch for each wondering why it came out that way. Will check, revert and branch out properly

**Comment by ujjwalagrawal17** [comment]
You need to create a seperate branch from master everytime.

**Comment by gconnect** [comment]
Okay. Thanks. Will do that.

**Pull request closed without merging**
