### PR TITLE
Course detail changes

### PR DESCRIPTION
**Pull request by MarinaTaran**
After merging #86 ,there is a minor UI issue in activity_course_detail, we are unable to see the top layout of fragment, it is getting hidden below the toolbar, tablayout.
befor
Screenshot_1570717087
after
Screenshot_1570706175

### CODE REVIEW

**Comment by MarinaTaran** [comment]
@ujjwalagrawal17 pleas can you check this one I compared it to fork

**Comment by MarinaTaran** [comment]
I added to ViewPager  just this two lines 
android:layout_width="match_parent"
 app:layout_constraintTop_toBottomOf="@id/appBarLayout4" 
sorry for such uncomfortables

**Comment by ujjwalagrawal17** [comment]
Doesn't seems to work fine in my PC- the line between tab, viewpager was missing and is not looking good. Also, The viewpager should never be inside appbarlayout.

**Comment by ujjwalagrawal17** [comment]
Thanks for your effort @MarinaTaran . Please pick other issues. This solution wasn't working properly.

**Pull request closed without merging**
