### PR TITLE
presenterCallback and related files modified

### LINKED ISSUE #291: Convert PresenterCallback.java to kotlin
**Describe the feature you'd like**

Convert PresenterCallback.java to kotlin

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by mistervaibhav**
## What this PR does
Fixes #291

### CODE REVIEW

**Comment by mistervaibhav** [comment]
I converted PresenterCallback from java to Kotlin and also rectified the errors which followed the conversion and the IDE isn't showing any errors per se . Also , the app is running fine on my mobile , however I am unsure of the issues raised through checks after i made the PR , and whether i need to perform more rectifications and modifications.
Any suggestions and help will be very much appreciated. Thanks.

**Comment by ujjwalagrawal17** [comment]
Can you resolve the conflicts in the PR. @mistervaibhav

**Comment by ujjwalagrawal17** [comment]
Also, Codacy build is failing because the 2 functions in new PresenterCallback.kt don't have KDoc. Can you add that too.

**Comment by mistervaibhav** [comment]
I have resolved all the conflicts and also added kDoc for the respective functions.However , the travis CI build failed. @ujjwalagrawal17 I would require a little help here. Please suggest me what can i do to make the travis CI pass.

**Comment by ujjwalagrawal17** [comment]
https://travis-ci.org/WikiEducationFoundation/apps-android-wikiedudashboard/builds/637005876?utm_source=github_status&utm_medium=notification - lint issues are there. 

Can you run ./gradlew ktlintFormat. I think that should fix the issues.

**Comment by mistervaibhav** [comment]
I think all the issues are fixed now.

**Comment by ujjwalagrawal17** [comment]
Hi, @mistervaibhav I have solved the merge conflicts and merged the code via command line. Thanks for the PR.

**Pull request closed without merging**
