### PR TITLE
Addresses Issue #219: Alphabetize Active Campaigns list

### PR DESCRIPTION
**Pull request by melissasny1**
## What this PR does
Alphabetizes the Active Campaigns list in CampaignListFragment.kt to make it easier to read.

## Screenshots
Before:
< add a screenshot of the UI before your change >
(page 1 of 8)
BEFORE CAMPAIGN LIST

After:
< add a screenshot of the UI after your change >
(page 1 of 8)
AFTER CAMPAIGN LIST

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
I guess there is some reason we are showing that sorting order. @ragesoss can you tell in which sorting order the campaign list is coming?

**Comment by ragesoss** [comment]
@ujjwalagrawal17 which campaigns list?

The list of current campaigns on the `/explore` page is ordered by number of courses.

The campaigns index page at `/campaigns` shows all campaigns, ordered by ID.

I think alphabetical makes sense for the app.

**Comment by melissasny1** [comment]
To clarify, I was referring the the Active Campaigns list on the Explore page.  If you want to make this change, I could do the same for the Active Courses list on the Explore page, too.

**Comment by ragesoss** [comment]
I think the current ordering, by number of programs, is what we want to keep for the Explore page.

**Comment by melissasny1** [comment]
Ok, thanks for the response, Sage.  As someone new to looking at the Explore page in the app, I'd suggest it might be helpful to let the app user know how the "Active Campaigns" and "Active Courses" lists are sorted if they're left as-is.  A user who is looking for a specific campaign or course title may have to look through the whole list to find it, and a user who's browsing the lists may find it useful to know how the lists are ordered.

**Comment by ujjwalagrawal17** [comment]
@melissasny I think if we can add more details in the course card item they will be able to find it useful.

**Comment by ujjwalagrawal17** [comment]
I guess we don't want to change the sorting order so closing this PR. Thanks for your effort. Let's continue the discussion on #219 for this.

**Pull request closed without merging**
