### PR TITLE
Fixes #212

### PR DESCRIPTION
**Pull request by Anniekobia**
**What this PR does**
1. Changed fragment_training.xml outer layout to Constraint layout
2. Changed nested Linearlayouts in fragment_training.xml to ConstraintLayouts 
3. Changed layout ID's from ll to cl

**Reference**
Fixes #212 

**Screenshots**
UI remains the same

### CODE REVIEW

**Comment by Anniekobia** [comment]
@ujjwalagrawal17 @ragesoss I have done the corrections on the PR. Kindly go through them and give feedbacl

**Comment by Anniekobia** [comment]
@ujjwalagrawal17 I have done the corrections. Please look at it.

**Comment by Anniekobia** [comment]
@ujjwalagrawal17 @ragesoss I did the corrections on the typecasting error that was causing the crash on ProfileFragment. The app still crashes but the error is coming from the main branch. My branch is in sync with the master. Kindly review the PR and advise

**Comment by ujjwalagrawal17** [comment]
I will have a look at it tomorrow @anniekobia

**Comment by ujjwalagrawal17** [comment]
@Anniekobia the profile fragment UI seems to be disturbed. Can you attach a screenshot of the UI if it's working fine there.

**Comment by ujjwalagrawal17** [comment]
Also, Please pull from master before testing.

**Comment by Anniekobia** [comment]
It works fine. Here is the screenshot
profile

**Comment by ujjwalagrawal17** [comment]
Screenshot_20191121-191416
Screenshot_20191121-191422


It should ideally look like this. Please resolve the bugs.

**Comment by Anniekobia** [comment]
Alright.Will work on it

**Comment by ujjwalagrawal17** [comment]
Any Update on this @Anniekobia? If you are still interested in the issue, please re-open the PR. Thanks for your effort.

**Pull request closed without merging**
