### PR TITLE
Use Kotlin BuildSrc to Manage dependency version

### LINKED ISSUE #271: Use variables to manage gradle android dependencies library version numbers
**Use variables to manage gradle android dependencies library version numbers**

- At the moment some of the version numbers are hardcoded as 1.0.2 etc

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by gconnect**
**What this PR does**
Fixes #271 
- Managed the Gradle dependencies version using Kotlin buildSrc

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
@glory can you put the build folder in gitignore.

**Comment by gconnect** [comment]
> @gconnect can you put the build folder in gitignore.

build folder is already in gitinore or are you refering to the buildSrc folder?

**Comment by ujjwalagrawal17** [comment]
I was asking about buildSrc/build folder. I think the files are not removed yet. 

 You can use 'git rm buildSrc/build' to remove it along with adding it in gitignore.

**Comment by ujjwalagrawal17** [comment]
The PR is perfect @gconnect . Thanks 

 Just 1 thing you can take care from next time onwards is 

**PR title should be :** 
Fixes #issueNumber (Issue Description)

**Description should contain:** 
Fixes #issueNumber

**Pull request merged**
