### PR TITLE
Use kotlin Data classes and remove overridden toString and other methods.

### PR DESCRIPTION
**Pull request by kulloveth**
fixes issue #313 
Removed overriden toString methods and used kotlin data class

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
@kulloveth Thanks for the PR! lint check is failing. Can you run `./gradlew ktlintFormat` and push your code after that.

**Comment by kulloveth** [comment]
> @kulloveth Thanks for the PR! lint check is failing. Can you run `./gradlew ktlintFormat` and push your code after that.

You can check it out now

**Comment by kulloveth** [comment]
@ujjwalagrawal17 so do i have to do this every time before i push?

**Comment by ujjwalagrawal17** [comment]
Yes, @kulloveth we need to run it everytime.

**Comment by ujjwalagrawal17** [comment]
Thanks for the PR! Nice Job.

**Pull request merged**
