### PR TITLE
Creating Account

### LINKED ISSUE #81: Write Documentation for newcomers to easily get started with the project
**Describe the feature you'd like**

Write documentation for newcomers to: 
1. Setup Android App.
2. Creating Account, Login to the dashboard.
3. Joining a course using dashboard website. 

Any other thing that new comers need.

### PR DESCRIPTION
**Pull request by vivekvj18**
Fixes #81 

Before:
Screenshot (73)

After:
Screenshot (76)

### CODE REVIEW

**Comment by gconnect** [comment]
I suggest you take a look at the app from the on-boarding to the signup and login with Wikieducation and outreach dashboard. That will enable you to give a clearer explanation of the account setup process.

I noticed you are capitalizing the first letter of each word in your write up. it shouldn't be like that. And also be careful with your spellings. You spelt Wikipedia wrongly multiple times.

**Comment by vivekvj18** [comment]
@gconnect 
can i get the path of the on-boarding section...?

**Comment by vivekvj18** [comment]
@gconnect 
The content i write for creating account is satisfied or it needs some changes...?
yes i know that i had to make a new file for Joining a course...

**Comment by gconnect** [comment]
> @gconnect
> can i get the path of the on-boarding section...?

Install the app to understand the setup flow

**Comment by gconnect** [comment]
> @gconnect
> The content i write for creating account is satisfied or it needs some changes...?
> yes i know that i had to make a new file for Joining a course...

The content is not satisfactory enough. It needs to be more descriptive.

**Comment by vivekvj18** [comment]
@gconnect 
as i click on the sign up button there comes the error
WhatsApp Image 2020-05-12 at 12 17 32 PM
Tell me what i can do with it and what should be written in support of it.

**Comment by vivekvj18** [comment]
@gconnect 
what needs to be done now...?

**Comment by ujjwalagrawal17** [comment]
Merging it for now. More improvements can be sent in next PR ! Thanks @vivekvj18

**Pull request merged**
