### PR TITLE
fixes issue #149

### PR DESCRIPTION
**Pull request by amitYadavDev**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
Fixes #issueNumber

< describe the purpose of this pull request and note the issue it addresses >

## Screenshots
Before:
< add a screenshot of the UI before your change >

After:
< add a screenshot of the UI after your change >
## Open questions and concerns
< anything you learned that you want to share, or questions you're wondering about related to this PR >

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
Thanks @amit6663 

Can you add the screenshots, other details in the PR template. Will be easy to review.

**Comment by amit6663** [comment]
Screenshot from 2020-01-11 14-40-12

**Comment by amit6663** [comment]
Screenshot from 2020-01-11 14-40-30

**Comment by amit6663** [comment]
@ujjwalagrawal17 now check

**Comment by ujjwalagrawal17** [comment]
@amit6663 I have mentioned some points in slack. Let me know if you haven't found the issues there.

**Comment by amit6663** [comment]
@u

**Comment by amit6663** [comment]
@u

**Review by ujjwalagrawal17 — CHANGES_REQUESTED** [review]
Please make sure UI is same as it was before.

**Comment by amit6663** [comment]
> Please make sure UI is same as it was before.

yes, absolutely

**Comment by amit6663** [comment]
@ujjwalagrawal17 can u tell me why not merge it?

**Comment by ujjwalagrawal17** [comment]
> @ujjwalagrawal17 can u tell me why not merge it?

Your PR has some UI issues so we can't merge it. Please check the UI in the current master branch, your branch by running it on your mobile. If it's looking the same/better, we will like to merge it.

**Comment by ujjwalagrawal17** [comment]
Also, from next PR onwards please follow the PR template. You haven't filled the details there. 
Screenshot 2020-01-16 at 9 23 23 pm

**Comment by ujjwalagrawal17** [comment]
Closing due to inactivity.

**Pull request closed without merging**
