### PR TITLE
feat: Add Download Image Option

### PR DESCRIPTION
**Pull request by kiranofans**
## What this PR does
Feature related: #61 
I'm trying to implement downloadImage() function for MediaDetailFragment.kt with following requirements:
1. Having storage permission
2. Create a folder to download images from the app, and download the image in that folder
3. Send notification that download has started and shared the progress of it
5. Remove the previous notification and send a notification to the user that image is download

#### What I have implemented and tested:
**Edit:**
- The permission problem solved, it will download the image right after the permission granted.
- The app can create folders in internal storage now, and the image will be downloaded into that folder, usually in `wikiedu/images/storage/emulated/0/`.
- Used download notification from DowloadManager, so when downloading, the notification will show downloading, and once it's complete, the notification will show download complete.
-------------------------------------------------
#### The problems I'm facing now:
1. I'm now trying to create a new folder while downloading an image and add storage permission.
By using the Android emulator, I can see that the folder is created, but the image wasn't stored in that folder.
2. When I tried to add storage permission to the MediaDetailFragment.kt, I got a problem with the Context in `ContextCompat.checkSelfPermission(Context, String permission)`

### CODE REVIEW

**Comment by kulloveth** [comment]
@kiranofans  check if this will be useful https://developer.android.com/training/permissions/requesting
and https://stackoverflow.com/questions/36011145/android-targetsdkversion-23-checkselfpermission-method

**Comment by kiranofans** [comment]
> @kiranofans check if this will be useful https://developer.android.com/training/permissions/requesting
> and https://stackoverflow.com/questions/36011145/android-targetsdkversion-23-checkselfpermission-method

Thanks! I will check this later

**Comment by gconnect** [comment]
Can you screenshot the error message you are getting?

**Comment by kiranofans** [comment]
@gconnect about creating the folder?

**Comment by kulloveth** [comment]
@kiranofans whats the progress

**Comment by ujjwalagrawal17** [comment]
@kiranofans any update on this PR ?

**Comment by kiranofans** [comment]
@ujjwalagrawal17 yes added download notification and permission, still got problem with creating folders in sdcard

**Comment by kiranofans** [comment]
@ujjwalagrawal17 added new commit, please check

**Comment by ujjwalagrawal17** [comment]
Thanks for the PR @kiranofans ! Works perfectly in Android 9.

**Pull request merged**
