### PR TITLE
ParentLayout id changed

### PR DESCRIPTION
**Pull request by kulloveth**
I changed the ConstraintLayout id from relativeLayout2 to constraintLayout

### CODE REVIEW

**Comment by kulloveth** [comment]
Kindly review my pull request  and give feedback @ujjwalagrawal17

**Comment by kulloveth** [comment]
@ujjwalagrawal17  kindly check this out, I think the pull request for #64  and #66  are together here

**Comment by ujjwalagrawal17** [comment]
The new layout seems similar in design but the click area of TextViews are reduced which will lead to bad user experience i.e they will feel clicks are not working if they click on right side. 

image

**Comment by ujjwalagrawal17** [comment]
@kulloveth can you increase the width of all the textviews.

**Comment by ujjwalagrawal17** [comment]
Other changes are good.

**Comment by ujjwalagrawal17** [comment]
> @ujjwalagrawal17 kindly check this out, I think the pull request for #64 and #66 are together here

Yes, it should Ideally have 2 separate PRs.

**Comment by kulloveth** [comment]
Ok, working on it

**Comment by ujjwalagrawal17** [comment]
Also, can you add a scroll view. It doesn't seem to work well with small phones.

**Comment by kulloveth** [comment]
> Also, can you add a scroll view. It doesn't seem to work well with small phones.

I will add a scrollView, what about using matchParent on The textViews ?

**Comment by ujjwalagrawal17** [comment]
Yes that too we need to increase.

**Comment by ujjwalagrawal17** [comment]
Repeated PR.

**Pull request closed without merging**
