### PR TITLE
#56 Profile page scrolling issue

### PR DESCRIPTION
**Pull request by gemasr**
## What this PR does

This PR is related to issue #56 

In this PR I have included some improvements done in the Profile related fragments (use of synthetic properties, handling of nullables, etc..)

The `fragment_profile_stats.xml` layout has been also changed to use a single `ConstraintLayout` instead multiple nested `LinearLayouts` as it seemed to be the main culprit for the scrolling issue.

I have not included Screenshots as nothing has changed UI wise 😊

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
Hi @gemasr can you resolve the merge conflicts.

**Comment by gemasr** [comment]
Hi! I have just resolved them

**Comment by ujjwalagrawal17** [comment]
@gemasr App is crashing in explore page in your branch. Can you fix that.

**Comment by gconnect** [comment]
@gemasr are you still working on this?

**Comment by ujjwalagrawal17** [comment]
@gemasr since the PR looks inactive from quite a few days, I am closing this for now. If you are still interested to work on it. Feel free to re-open and do the necessary modifications. 

Thanks for your effort!

**Pull request closed without merging**
