### PR TITLE
Add Google Play badge, link in readme.

### PR DESCRIPTION
**Pull request by kulloveth**
to solve #166
 
click on badge to download app

### CODE REVIEW

**Comment by gconnect** [comment]
@kulloveth check Codacy PR Quality Review Error Message

**Comment by kulloveth** [comment]
> @kulloveth check Codacy PR Quality Review Error Message

thanks fixed

**Comment by ujjwalagrawal17** [comment]
we want to put the badge along with other badges not at the last. @kulloveth can you modify the PR accordingly.

**Comment by kulloveth** [comment]
@ujjwalagrawal17  is it ok like this?

**Comment by ujjwalagrawal17** [comment]
Yup !

**Comment by ujjwalagrawal17** [comment]
Thanks @kulloveth

**Pull request merged**
