### PR TITLE
#131 Kotlin Standart Function 

### PR DESCRIPTION
**Pull request by victorvicari**
Added a `extension fuction` for `filtered a list` and set up direclty into the `adapters`. Also I've used of `kotlin iterators`. The avoid the boilerplate, make use of `kotlin standart function`, mostly `apply`. once that is very useful to setup `property values`.

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
@victorvicari can you resolve merge conflicts. Also, there is some UI issue in the media details page (recycler views) after your previous PR merge. Can you have a look into it?

**Comment by victorvicari** [comment]
At uploads, some items are missing... but I touched only in the items_layouts, not the recycler_view itself. This is what you are talking about it?

**Comment by ujjwalagrawal17** [comment]
@victorvicari  I will create a separate issue for that.

**Comment by ujjwalagrawal17** [comment]
Nice Job !

**Pull request merged**
