### PR TITLE
feat: Format the Start and End Date to Human Readable Dates on the Active Course Detailed Page

### LINKED ISSUE #158: Format the Start and End Date to Human Readable Dates on the Active Course Detailed Page
**Format the Start and End Date to Human Readable Dates**
- The current start and end date  of the Active Course Detailed Page is not human-readable

### PR DESCRIPTION
**Pull request by kulloveth**
Fixes #158 

## What  I learnt
* document public methods
* methods that dont need to be accessible should be private
Before
dateB

After
dateA

### CODE REVIEW

**Comment by kulloveth** [comment]
@ujjwalagrawal17  how do i fix undocumented public function error?

**Comment by kulloveth** [comment]
> @ujjwalagrawal17 how do i fix undocumented public function error?

figured it out

**Comment by gconnect** [comment]
@kulloveth What I meant by human-readable is that the date should be in this format 2019-12-31
Thu 24 Dec 2019 or 24 Dec 2019

**Comment by kulloveth** [comment]
After

**Pull request merged**
