### PR TITLE
#90 Remove Kotlin NPE

### PR DESCRIPTION
**Pull request by victorvicari**
removed kotlin NPE from code base. Instead, use Null safe

### CODE REVIEW

**Comment by ujjwalagrawal17** [comment]
The app is crashing on opening profile Fragment. 

**Relevant Logs:** 

`2019-10-04 00:27:44.001 21103-21103/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wikiedufoundation.wikiedudashboard.release, PID: 21103
    java.lang.IllegalStateException: Fragment ProfileFragment{7370d08} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.view.ProfileFragment.setProfileData(ProfileFragment.kt:148)
        at org.wikiedufoundation.wikiedudashboard.ui.coursedetail.recentactivity.ProfilePresenterImpl$requestProfileDetails$1.onSuccess(ProfilePresenterImpl.kt:20)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.RetrofitProfileProvider$requestProfileDetails$1.onResponse(RetrofitProfileProvider.kt:40)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
2019-10-04 00:30:54.812 21594-21594/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wikiedufoundation.wikiedudashboard.release, PID: 21594
    java.lang.IllegalStateException: Fragment ProfileFragment{caea7fa} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.view.ProfileFragment.setProfileData(ProfileFragment.kt:148)
        at org.wikiedufoundation.wikiedudashboard.ui.coursedetail.recentactivity.ProfilePresenterImpl$requestProfileDetails$1.onSuccess(ProfilePresenterImpl.kt:20)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.RetrofitProfileProvider$requestProfileDetails$1.onResponse(RetrofitProfileProvider.kt:40)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
2019-10-04 00:31:48.042 8459-8496/? E/BatteryStatsService: no controller energy info supplied`

**Device:**
Pixel 3 Emulator - API 25 

I guess you aren't enrolled in any course yet.

**Comment by ujjwalagrawal17** [comment]
@victorvicari Can you share your email address. Will send you an invite for our Slack channel.

**Comment by ujjwalagrawal17** [comment]
Also, there are some conflicts after merging other PRs. Can you resolve them @victorvicari ?

**Comment by victorvicari** [comment]
about the crash... i'll take a look in a few hours.

**Comment by ujjwalagrawal17** [comment]
I will try to review it soon.

**Comment by ujjwalagrawal17** [comment]
nice work. Thanks, @victorvicari

**Pull request merged**
