### PR TITLE
work on issue #86 UI issue in activity_course_detail

### PR DESCRIPTION
**Pull request by MarinaTaran**
NOTE: Please review the pull request process before opening your first PR: https://github.com/WikiEducationFoundation/apps-android-wikiedudashboard/blob/master/CONTRIBUTING.md#pull-request-process

## What this PR does
< describe the purpose of this pull request and note the issue it addresses >

## Screenshots
Before:
< add a screenshot of the UI before your change >

After:
< add a screenshot of the UI after your change >
## Open questions and concerns
< anything you learned that you want to share, or questions you're wondering about related to this PR >

### CODE REVIEW

**Comment by kulloveth** [comment]
hey @MarinaTaran  kindly read through the PR process and restructure your PR and also figure out what the conflicts

**Comment by MarinaTaran** [comment]
After merging #86 ,there is a minor UI issue in activity_course_detail, we are unable to see the top layout of fragment, it is getting hidden below the toolbar, tablayout.
befor changes
Screenshot_1570717087
after changes
Screenshot_1570706175

**Comment by MarinaTaran** [comment]
in fork we still have relativelayout ,but in "code" it is constraintlayout,so when i take fork I change relative to constraint and when i push i have conflict

**Comment by kulloveth** [comment]
> in fork we still have relativelayout ,but in "code" it is constraintlayout,so when i take fork I change relative to constraint and when i push i have conflict

how is that possible, well i think everything is ok now change the PR title too to be related to the issue

**Comment by ujjwalagrawal17** [comment]
I see only 3 whitespaces are added in this PR. Correct me if I am wrong.

**Comment by kulloveth** [comment]
@MarinaTaran  do you mind if I fix this?

**Comment by MarinaTaran** [comment]
@ujjwalagrawal17  what does it means  3 whitespaces

**Comment by ujjwalagrawal17** [comment]
Please check the changes made by you once.

**Comment by MarinaTaran** [comment]
@kulloveth yes,why not

**Comment by MarinaTaran** [comment]
but still,I want to ask when I take fork I have inside code like this

and we have originaly such a code

is this posible that this dose in my PR conflict?

**Comment by ujjwalagrawal17** [comment]
not relevant now.

**Pull request closed without merging**
