### PR TITLE
Fix: removed all hardcoded values

### LINKED ISSUE #84: The Hardcoded strings should be changed to use @String resources

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes: #84 
In this pr, I have removed the hardcoded strings and also the values of the dimensions along with it.

**Before**
The string values were hardcoded

**After**
The string values are have replaced by the id in strings.xml and also dimens likewise.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@gconnect Please review Ma'am

**Review by gconnect — COMMENTED** [review]
Looks good to me. However you will need to fix Travis error.

**Comment by Bhavnaharitsa** [comment]
@gconnect I have run the command "gradlew check" on my terminal. Could you please help me with spotting the exact error?

**Comment by gconnect** [comment]
> @gconnect I have run the command "gradlew check" on my terminal. Could you please help me with spotting the exact error?

 Fix this error 
image

Then run Run this command ./gradlew ktlintFormat

**Comment by ujjwalagrawal17** [comment]
Hi @Bhavnaharitsa thanks for sending the PR ! Changes looks good to me, merging them.

**Pull request merged**
