### PR TITLE
Replace Toast with Snackbars

### LINKED ISSUE #312: Replace Toast with Snackbars
Replace Toast messages with snackbars in all pages.

### PR DESCRIPTION
**Pull request by kulloveth**
fix #312

### CODE REVIEW

**Comment by kulloveth** [comment]
@ujjwalagrawal17  any clue to why this is failing
Task :app:ktlintMainSourceSetFormat FAILED

**Comment by gconnect** [comment]
@kulloveth have you done lint check ./gradlew ktlintFormat? If yes. Check this line on your code wikiedudashboard/app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/ViewUtils.kt:21:1: Wildcard import (cannot be auto-corrected)

**Comment by kulloveth** [comment]
> @kulloveth have you done lint check ./gradlew ktlintFormat? If yes. Check this line on your code wikiedudashboard/app/src/main/java/org/wikiedufoundation/wikiedudashboard/util/ViewUtils.kt:21:1: Wildcard import (cannot be auto-corrected)

Oh! thanks, fixed

**Comment by gconnect** [comment]
This looks good to me. Does this PR fix all  fragment and activity where toast was initially used to snackbar?

**Comment by kulloveth** [comment]
> This looks good to me. Does this PR fix all fragment and activity where toast was initially used to snackbar?

Yes

**Comment by ujjwalagrawal17** [comment]
Looks great to me. Merging it. Thanks @kulloveth for the contribution.

**Pull request merged**
